# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: branch_protection_sdks
description: Organization branch protection policy for Microsoft Graph Toolkit repository
resource: repository
configuration:
  branchProtectionRules:
  - branchNamePattern: next/*
    requiredApprovingReviewsCount:
      min: 1
    # Must have a CODEOWNER approve for the PR to be merged.
    requireCodeOwnersReview: true
    
    # Dismiss stale pull request approvals when new commits are pushed
    dismissStaleReviews: true
    
    # Require conversation resolution before merging. Address all concerns, and resolve in the GitHub PR UI.
    requiresConversationResolution: true

    # Require status checks to pass before merging. TODO: this value should be true, we should work to support this.
    # Used with the requiredStatusChecks setting to specify which checks must pass for the PR to be merged.
    requiresStrictStatusChecks: true

    requiredStatusChecks:
    - GitOps/AdvancedSecurity
    - license/cla
    - 'Build pr / build (16.x)'
    
    # TODO: all commits should be signed. We need to get everyone signing their commits.
    requiresCommitSignatures: false
