/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface M365Agenda {}
  interface M365AgendaAttributes extends StencilHTMLAttributes {}

  interface M365TestAuth {}
  interface M365TestAuthAttributes extends StencilHTMLAttributes {}

  interface M365Login {
    'login': () => Promise<void>;
    'logout': () => Promise<void>;
  }
  interface M365LoginAttributes extends StencilHTMLAttributes {}

  interface M365MsalProvider {
    'clientId': string;
    'loginType': string;
  }
  interface M365MsalProviderAttributes extends StencilHTMLAttributes {
    'clientId'?: string;
    'loginType'?: string;
  }

  interface M365WamProvider {
    'clientId': string;
  }
  interface M365WamProviderAttributes extends StencilHTMLAttributes {
    'clientId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'M365Agenda': Components.M365Agenda;
    'M365TestAuth': Components.M365TestAuth;
    'M365Login': Components.M365Login;
    'M365MsalProvider': Components.M365MsalProvider;
    'M365WamProvider': Components.M365WamProvider;
  }

  interface StencilIntrinsicElements {
    'm365-agenda': Components.M365AgendaAttributes;
    'm365-test-auth': Components.M365TestAuthAttributes;
    'm365-login': Components.M365LoginAttributes;
    'm365-msal-provider': Components.M365MsalProviderAttributes;
    'm365-wam-provider': Components.M365WamProviderAttributes;
  }


  interface HTMLM365AgendaElement extends Components.M365Agenda, HTMLStencilElement {}
  var HTMLM365AgendaElement: {
    prototype: HTMLM365AgendaElement;
    new (): HTMLM365AgendaElement;
  };

  interface HTMLM365TestAuthElement extends Components.M365TestAuth, HTMLStencilElement {}
  var HTMLM365TestAuthElement: {
    prototype: HTMLM365TestAuthElement;
    new (): HTMLM365TestAuthElement;
  };

  interface HTMLM365LoginElement extends Components.M365Login, HTMLStencilElement {}
  var HTMLM365LoginElement: {
    prototype: HTMLM365LoginElement;
    new (): HTMLM365LoginElement;
  };

  interface HTMLM365MsalProviderElement extends Components.M365MsalProvider, HTMLStencilElement {}
  var HTMLM365MsalProviderElement: {
    prototype: HTMLM365MsalProviderElement;
    new (): HTMLM365MsalProviderElement;
  };

  interface HTMLM365WamProviderElement extends Components.M365WamProvider, HTMLStencilElement {}
  var HTMLM365WamProviderElement: {
    prototype: HTMLM365WamProviderElement;
    new (): HTMLM365WamProviderElement;
  };

  interface HTMLElementTagNameMap {
    'm365-agenda': HTMLM365AgendaElement
    'm365-test-auth': HTMLM365TestAuthElement
    'm365-login': HTMLM365LoginElement
    'm365-msal-provider': HTMLM365MsalProviderElement
    'm365-wam-provider': HTMLM365WamProviderElement
  }

  interface ElementTagNameMap {
    'm365-agenda': HTMLM365AgendaElement;
    'm365-test-auth': HTMLM365TestAuthElement;
    'm365-login': HTMLM365LoginElement;
    'm365-msal-provider': HTMLM365MsalProviderElement;
    'm365-wam-provider': HTMLM365WamProviderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
