/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyDay {}
  interface MyDayAttributes extends StencilHTMLAttributes {}

  interface MyFakeAuth {}
  interface MyFakeAuthAttributes extends StencilHTMLAttributes {}

  interface MyLogin {
    'login': () => Promise<void>;
    'logout': () => Promise<void>;
  }
  interface MyLoginAttributes extends StencilHTMLAttributes {}

  interface MyMsalProvider {
    'clientId': string;
    'loginType': string;
  }
  interface MyMsalProviderAttributes extends StencilHTMLAttributes {
    'clientId'?: string;
    'loginType'?: string;
  }

  interface MyWamProvider {
    'clientId': string;
  }
  interface MyWamProviderAttributes extends StencilHTMLAttributes {
    'clientId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyDay': Components.MyDay;
    'MyFakeAuth': Components.MyFakeAuth;
    'MyLogin': Components.MyLogin;
    'MyMsalProvider': Components.MyMsalProvider;
    'MyWamProvider': Components.MyWamProvider;
  }

  interface StencilIntrinsicElements {
    'my-day': Components.MyDayAttributes;
    'my-fake-auth': Components.MyFakeAuthAttributes;
    'my-login': Components.MyLoginAttributes;
    'my-msal-provider': Components.MyMsalProviderAttributes;
    'my-wam-provider': Components.MyWamProviderAttributes;
  }


  interface HTMLMyDayElement extends Components.MyDay, HTMLStencilElement {}
  var HTMLMyDayElement: {
    prototype: HTMLMyDayElement;
    new (): HTMLMyDayElement;
  };

  interface HTMLMyFakeAuthElement extends Components.MyFakeAuth, HTMLStencilElement {}
  var HTMLMyFakeAuthElement: {
    prototype: HTMLMyFakeAuthElement;
    new (): HTMLMyFakeAuthElement;
  };

  interface HTMLMyLoginElement extends Components.MyLogin, HTMLStencilElement {}
  var HTMLMyLoginElement: {
    prototype: HTMLMyLoginElement;
    new (): HTMLMyLoginElement;
  };

  interface HTMLMyMsalProviderElement extends Components.MyMsalProvider, HTMLStencilElement {}
  var HTMLMyMsalProviderElement: {
    prototype: HTMLMyMsalProviderElement;
    new (): HTMLMyMsalProviderElement;
  };

  interface HTMLMyWamProviderElement extends Components.MyWamProvider, HTMLStencilElement {}
  var HTMLMyWamProviderElement: {
    prototype: HTMLMyWamProviderElement;
    new (): HTMLMyWamProviderElement;
  };

  interface HTMLElementTagNameMap {
    'my-day': HTMLMyDayElement
    'my-fake-auth': HTMLMyFakeAuthElement
    'my-login': HTMLMyLoginElement
    'my-msal-provider': HTMLMyMsalProviderElement
    'my-wam-provider': HTMLMyWamProviderElement
  }

  interface ElementTagNameMap {
    'my-day': HTMLMyDayElement;
    'my-fake-auth': HTMLMyFakeAuthElement;
    'my-login': HTMLMyLoginElement;
    'my-msal-provider': HTMLMyMsalProviderElement;
    'my-wam-provider': HTMLMyWamProviderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
