# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run prepare
    - run: npm run pack
    - name: Upload a Build Artifact - package
      uses: actions/upload-artifact@v2
      with:
        name: npm-package
        path: packages/mgt/microsoft-mgt-*.tgz
    - name: Upload a Build Artifact - bundle
      uses: actions/upload-artifact@v2
      with:
        name: bundle
        path: packages/mgt/dist/bundle
