# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Clean pr deployments

on:
  pull_request:
    types: [closed]
    branches: [main, release/**, next/**]

jobs:
  cleanup:
    if: "contains(github.event.pull_request.labels.*.name, 'Build: Storybook') || contains(github.event.pull_request.labels.*.name, 'Build: React Contoso')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Remove pr storybook deployment
        if: "contains(github.event.pull_request.labels.*.name, 'Build: Storybook')"
        run: |
          git rm -r next/pr/${{ github.event.number }}
          git commit -m "PR ${{ github.event.number }} closed - remove storybook"
      - name: Remove pr test app deployment
        if: "contains(github.event.pull_request.labels.*.name, 'Build: React Contoso')"
        run: |
          git rm -r next/sample/pr/${{ github.event.number }}
          git commit -m "PR ${{ github.event.number }} closed - remove react-contoso"
      - name: Push changes
        run: |
          git push
