# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy next/fluentui storybook

on:
  push:
    branches: [next/fluentui]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'microsoftgraph/microsoft-graph-toolkit'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Build 🛠
        run: |
          npm install -g yarn lerna
          yarn
          yarn build
          yarn storybook:build

      - name: Deploy mgt.dev/next 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: storybook-static
          target-folder: next/v3
          token: ${{ secrets.GITHUB_TOKEN }}
